export const CREATE_FUNCIONARIO = "CREATE_FUNCIONARIO";

export const RETRIEVE_FUNCIONARIOS = "RETRIEVE_FUNCIONARIOS";

export const UPDATE_FUNCIONARIO = "UPDATE_FUNCIONARIO";

export const DELETE_FUNCIONARIO = "DELETE_FUNCIONARIO";