export const CREATE_SERVICO = "CREATE_SERVICO";

export const RETRIEVE_SERVICOS = "RETRIEVE_SERVICOS";

export const UPDATE_SERVICO = "UPDATE_SERVICO";

export const DELETE_SERVICO = "DELETE_SERVICO";