export const CREATE_ESTOQUE = "CREATE_ESTOQUE";

export const RETRIEVE_ESTOQUES = "RETRIEVE_ESTOQUES";

export const UPDATE_ESTOQUE = "UPDATE_ESTOQUE";

export const DELETE_ESTOQUE = "DELETE_ESTOQUE";