export const CREATE_PACIENTE = "CREATE_PACIENTE";

export const RETRIEVE_PACIENTES = "RETRIEVE_PACIENTES";

export const UPDATE_PACIENTE = "UPDATE_PACIENTE";

export const DELETE_PACIENTE = "DELETE_PACIENTE";